# Generated by Django 5.0.3 on 2024-06-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0002_assignmentfile_submissionfile_alter_classroom_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='oV80Ld', max_length=6, unique=True),
        ),
    ]
