# Generated by Django 5.0.3 on 2024-06-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0003_alter_classroom_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='VtEV2e', max_length=6, unique=True),
        ),
    ]
