# Generated by Django 5.0.3 on 2024-06-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0008_alter_classroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='s1lo9d', max_length=6, unique=True),
        ),
    ]
