# Generated by Django 5.0.3 on 2024-04-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_is_admin_useraccount_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_superuser',
        ),
    ]
