# Generated by Django 5.0.3 on 2024-05-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_useraccount_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
